### ISSUE TITLE
download scripts missed

### ISSUE THREAD

**Issue by eps696** [Ha0Tang/DAGAN#1]
hello, 
following readme commands like `sh scripts/download_dagan_model.sh [dataset]`, i cannot find the directory `scripts` (nor the scripts files). am i missing something or the readme is outdated?

**Comment by Ha0Tang** [comment]
Thanks for your interest in our work. Will upload the scripts and models tomorrow.

**Comment by Ha0Tang** [comment]
@eps696 Hi, I have uploaded everything including datasets, pre-trained models, and download scripts. Enjoy!!!
