### ISSUE TITLE
no_instance param is not working

### ISSUE THREAD

**Issue by chokyungjin** [Ha0Tang/DAGAN#3]
Hi, I'm so glad to meet your Paper and Code! 
But I have a question.
I tried to train with no_instance parameter, But the code has returned this error.
But I don't know why this is happening, Because in Pix2pixHD, which is similar to the code you configured on the custom dataloader, the no_instance parameter is working.

File "/home/user/.local/lib/python3.6/site-packages/torch/nn/init.py", line 282, in _calculate_fan_in_and_fan_out
    receptive_field_size = tensor[0][0].numel()
IndexError: index 0 is out of bounds for dimension 0 with size 0

One more question, I want to learn models using grayscale images, But the option does not have an input_nc option, only have output_nc. 

Thanks again!!

**Comment by Ha0Tang** [comment]
1. `--no_instance` should work, as shown [here](https://github.com/Ha0Tang/DAGAN/blob/master/DAGAN_v1/train_deepfashion.sh)

2. `--output_nc 1` is for grayscale images.
