### ISSUE TITLE
How to apply paired image to image translation this model?

### ISSUE THREAD

**Issue by chokyungjin** [Ha0Tang/DAGAN#4]
Hi, I'm so glad to meet your Paper and Code!
But I have a question.
I want to image to image translation this model like pix2pixHD, But I tested the model I trained and the result was input_label only returns the semantic mask and synthesized_image does not return anything. 
How Can I apply this model in Image to Image using paired dataset? 

Thanks again!!

**Comment by Ha0Tang** [comment]
Hi, our DAGAN is proposed for paired label-to-image translation tasks, which is very similar to the image-to-image translation task. So, I think it's quite easy to apply our model to the image-to-image translation task.

First, can you provide more details about your training, data structure, and hyper-parameters? Second, I would like to suggest you train our model on the provided datasets to see everything is right for you.

**Comment by chokyungjin** [comment]
Thanks quick reply. 
I actually want to train x-ray(grayscale) images. And I have two domains in my custom dataset like summer2winter.

My training hyperparameter scripts is
python train.py --name cityscapes --dataset_mode cityscapes --dataroot /workspace/1020_inference_train35/summer2winter/ --niter 100 --niter_decay 100 --gpu_ids 3 --checkpoints_dir ./checkpoints --batchSize 1 --save_epoch_freq 5  --save_latest_freq 1000 --phase train --preprocess_mode none --label_nc 0 --output_nc 1 --no_flip --load_size 1024 --crop_size 1024 --no_instance --netG pix2pixhd --contain_dontcare_label --nThreads 1 --no_vgg_loss

And my dataset structure is 
summer2winter
|
train
|
trainA /  trainB

I modified your code in base_dataset , pix2pix_dataset.py and visualizer.py.
Thanks again!

**Comment by Ha0Tang** [comment]
Can your model start training? What error did you encounter?

**Comment by chokyungjin** [comment]
I corrected the dataset.py code and the visualizer code, so there was no error.
But the results of the training show that synthesized_images are only one value.

![image](https://user-images.githubusercontent.com/46750574/97285844-17dd5e80-1886-11eb-85b4-384c0a6d534e.png)

**Comment by Ha0Tang** [comment]
can you share several samples of your real data pair?

**Comment by chokyungjin** [comment]
I want to show real_image data, but policy makes it hard to show dataset..
But I can show you input_label image and my synthesized_image results.
![image](https://user-images.githubusercontent.com/46750574/97286818-3132da80-1887-11eb-9e3c-6b411d8408a4.png)
![image](https://user-images.githubusercontent.com/46750574/97286831-355ef800-1887-11eb-9585-5d9ced38fcda.png)

**Comment by Ha0Tang** [comment]
what's the channel size of your input labels?

**Comment by chokyungjin** [comment]
I applyed --label_nc 0, --output_nc 1 options , and my dataset channel is 1024,1024,1

**Comment by Ha0Tang** [comment]
then --label_nc should be 1, I think

**Comment by chokyungjin** [comment]
Ok Thanks. I'll retry

**Comment by Ha0Tang** [comment]
Moreover, are you using this [line](https://github.com/Ha0Tang/DAGAN/blob/4a994bdb2dbf9d594692fb62f12cbe89aaa498b4/DAGAN_v1/models/networks/generator.py#L170), which may cause the grayscale outputs to be only one value.

**Comment by chokyungjin** [comment]
@Ha0Tang  Should I comment out that line?

**Comment by Ha0Tang** [comment]
what's the number of semantic classes of your input labels?

**Comment by Ha0Tang** [comment]
Yes or try other activation functions may work for you

**Comment by chokyungjin** [comment]
umm.. Actually, I don't have a semantic class on my label. So I gived --no_instance option.

**Comment by Ha0Tang** [comment]
I see, then --label_nc should be 1 instead of 0.

**Comment by chokyungjin** [comment]
Ok, Thanks!
I'll try!

**Comment by Ha0Tang** [comment]
And line [117-128](https://github.com/Ha0Tang/DAGAN/blob/4a994bdb2dbf9d594692fb62f12cbe89aaa498b4/DAGAN_v1/models/pix2pix_model.py#L117) should be removed.

**Comment by chokyungjin** [comment]
I'm so Sorry But one more question.
As you said, erasing 117-128 codes does not have an input_semantics value, so there is an error. 
What should I do?

**Comment by Ha0Tang** [comment]
replace `input_semantics` in line 130 with `data['label']` should work

**Comment by chokyungjin** [comment]
I tried you said before. But I couldn't solve it because I got input_semantics from here.
https://github.com/Ha0Tang/DAGAN/blob/4a994bdb2dbf9d594692fb62f12cbe89aaa498b4/DAGAN_v1/models/pix2pix_model.py#L42

**Comment by Ha0Tang** [comment]
show me the full error message

**Comment by chokyungjin** [comment]
my train script is
train.py --name x_ray_on_off_celeba --dataset_mode custom --label_dir /workspace/1020_inference_train35/summer2winter/train_A --label_nc 1 --no_instance --image_dir /workspace/1020_inference_train35/summer2winter/train_B --niter 50 --niter_decay 50 --gpu_ids 1 --checkpoints_dir ./checkpoints --batchSize 1 --save_epoch_freq 5 --save_latest_freq 1000 --phase train --preprocess_mode none --output_nc 1 --no_flip --load_size 1024 --crop_size 1024 --contain_dontcare_label --nThreads 1 --no_vgg_loss

and I modified 42 line like this
 real_image = self.preprocess_input(data)

but error message is 

Traceback (most recent call last):
  File "train.py", line 40, in <module>
    trainer.run_generator_one_step(data_i)
  File "/workspace/DAGAN/DAGAN_v1/trainers/pix2pix_trainer.py", line 35, in run_generator_one_step
    g_losses, generated = self.pix2pix_model(data, mode='generator')
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/DAGAN/DAGAN_v1/models/pix2pix_model.py", line 45, in forward
    real_image)
TypeError: compute_generator_loss() missing 1 required positional argument: 'real_image'

compute_generator_loss() function needs input_semantics.

**Comment by Ha0Tang** [comment]
you need to check line 45

**Comment by chokyungjin** [comment]
Yes. compute_generator_loss function need input_semantics because of self.generate_fake function.

https://github.com/Ha0Tang/DAGAN/blob/4a994bdb2dbf9d594692fb62f12cbe89aaa498b4/DAGAN_v1/models/pix2pix_model.py#L187-L200

**Comment by Ha0Tang** [comment]
I think you cannot do this
`and I modified 42 line like this
real_image = self.preprocess_input(data)`

since self.preprocess_input should also return `input_semantics`

**Comment by chokyungjin** [comment]
@Ha0Tang Thanks! I resolved only one value output image. 
But one more question,, results image is blurry. how can I resolve it?
my train param is 

python train.py --name x_ray_on_off_celeba --dataset_mode custom --label_dir \
/workspace/celeba_hq/train/train_A\
 --label_nc 1 --no_instance --image_dir /workspace/celeba_hq/train/train_B\
  --niter 50 --niter_decay 50 --gpu_ids 1 --checkpoints_dir ./checkpoints --batchSize 1 --save_epoch_freq 5 --save_latest_freq 1000\
  --phase train --preprocess_mode none --output_nc 1 --no_flip --load_size 1024 --crop_size 1024\
    --nThreads 1 --no_vgg_loss --netG pix2pixhd

**Comment by Ha0Tang** [comment]
Adding pixel reconstruction loss or vgg loss may work
