### ISSUE TITLE
Missing key(s) in state_dict

### ISSUE THREAD

**Issue by WenyuZhu** [Ha0Tang/DAGAN#5]
Hi, impressive work here. I would like to have an experiment on data augmentation with your code. However, when I followed instructions on your front page until 'sh test_ade.sh', it showed me: 
'' RuntimeError: Error(s) in loading state_dict for SPADEGenerator:
        Missing key(s) in state_dict: "channelAtt.conv1.weight", "channelAtt.conv1.bias", "channelAtt.conv2.weight", "channelAtt.conv2.bias". 
        Unexpected key(s) in state_dict: "cab.conv1.weight", "cab.conv1.bias", "cab.conv2.weight", "cab.conv2.bias". 

Do you have any idea about this issue?

**Comment by Ha0Tang** [comment]
Hi, have you solved this issue? and what's your pytorch version? it should be pytorch 1.0.

**Comment by Ha0Tang** [comment]
@WenyuZhu It works now, please try it again.
